TRIVIAL Fix failing build
Fix build. Issue was caused by CMS-15071.

The local build failed with the following error:
Error: projects/navapp/src/app/app.component.spec.ts:72:5 - error TS2741: Property 'helpLinks' is missing in type 'AppSettingsMock' but required in type 'AppSettings'.
[INFO]
[INFO] 72     appSettings = new AppSettingsMock();
[INFO]        ~~~~~~~~~~~
[INFO]
[INFO]   projects/navapp/src/app/models/dto/app-settings.dto.ts:81:3
[INFO]     81   helpLinks: NavAppHelpLink[];
[INFO]          ~~~~~~~~~
[INFO]     'helpLinks' is declared here.
[INFO]
[INFO]
[INFO] Error: projects/navapp/src/app/models/dto/app-settings.mock.ts:21:14 - error TS2420: Class 'AppSettingsMock' incorrectly implements interface 'AppSettings'.
[INFO]   Property 'helpLinks' is missing in type 'AppSettingsMock' but required in type 'AppSettings'.
[INFO]
[INFO] 21 export class AppSettingsMock implements AppSettings {
[INFO]                 ~~~~~~~~~~~~~~~
[INFO]
[INFO]   projects/navapp/src/app/models/dto/app-settings.dto.ts:81:3
[INFO]     81   helpLinks: NavAppHelpLink[];
[INFO]          ~~~~~~~~~
[INFO]     'helpLinks' is declared here.
[INFO]
[INFO]
[INFO] Error: projects/navapp/src/app/services/navigation.service.spec.ts:88:5 - error TS2322: Type 'AppSettingsMock' is not assignable to type 'AppSettings'.
[INFO]
[INFO] 88     appSettingsMock = new AppSettingsMock({